(define (problem one)
    (:domain plushistics)
    
    (:objects
        V1 V2 - van
        C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 - city
    )

    (:init
        (= (gas) 0)
        (= (capacity V1) 10)
        (= (capacity V2) 10)
        (= (cargo V1) 0)
        (= (cargo V2) 0)
        (path C1 C4)
        (path C1 C3)
        (path C1 C5)
        (path C4 C1)
        (path C3 C1)
        (path C5 C1)
        (path C2 C5)
        (path C5 C2)
        (path C3 C4)
        (path C4 C3)
        (path C4 C5)
        (path C5 C4)
        (path C6 C3)
        (path C3 C6)
        (path C7 C6)
        (path C6 C7)
        (path C7 C4)
        (path C4 C7)
        (path C4 C8)
        (path C8 C4)
        (path C4 C9)
        (path C9 C4)
        (path C9 C10)
        (= (sharks C1) 5)
        (= (sharks C2) 8)
        (= (sharks C3) 8)
        (= (sharks C4) 4)
        (= (sharks C5) 1)
        (= (sharks C6) 9)
        (= (sharks C7) 4)
        (= (sharks C8) 2)
        (= (sharks C9) 6)
        (= (sharks C10) 3)
        (= (demand C1) 7)
        (= (demand C2) 4)
        (= (demand C3) 2)
        (= (demand C4) 6)
        (= (demand C5) 2)
        (= (demand C6) 10)
        (= (demand C7) 1)
        (= (demand C8) 7)
        (= (demand C9) 2)
        (= (demand C10) 5)
        (= (cost C1 C4) 1)
        (= (cost C1 C3) 1)
        (= (cost C1 C5) 1)
        (= (cost C4 C1) 1)
        (= (cost C3 C1) 1)
        (= (cost C5 C1) 1)
        (= (cost C2 C5) 1)
        (= (cost C5 C2) 1)
        (= (cost C3 C4) 1)
        (= (cost C4 C3) 1)
        (= (cost C4 C5) 1)
        (= (cost C5 C4) 1)
        (= (cost C6 C3) 1)
        (= (cost C3 C6) 1)
        (= (cost C7 C6) 1)
        (= (cost C6 C7) 1)
        (= (cost C7 C4) 1)
        (= (cost C4 C7) 1)
        (= (cost C4 C8) 1)
        (= (cost C8 C4) 1)
        (= (cost C4 C9) 1)
        (= (cost C9 C4) 1)
        (= (cost C9 C10) 1)

    )

    (:goal
        (forall (?c - city)
            (>= (sharks ?c) (demand ?c))
        )
    )

    (:metric minimize
        (gas)
    )
)